### ISSUE TITLE
The code is not really useable in this format.

### ISSUE THREAD

**Issue by cbitterfield** [Rpinto02/Image_Rotator#1]
I am trying to get a more production project done. I have about 75,000 files that need to be rotated. If you have time can you send the rest of the files.

**Comment by Rpinto02** [comment]
The code was only meant to work under a jupyter notebook environment since it was a code challenge and there was no need to put it in production, so all the files are in the repository.
If you want the images as well, you can find the challenge [here](https://gist.github.com/csaftoiu/9fccaf47fd8f96cd378afd8fdd0d63c1).
Let me know what can I do to help.
